=== UMDSeniorDesign/Lifecycledocs/XML XSD XSLT/NotionalSchema2.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xi="http://www.w3.org/2001/XInclude"
    elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xsd:element name="ProjectLifecycleDocuments" type="ProjectLifecycleDocumentsType"/>
    <xsd:complexType name="ProjectLifecycleDocumentsType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="SoftwareRequirementsDocument"/>
            <xsd:element ref="UseCaseDocument"/>
            <xsd:element ref="TestCaseDocument"/>
        </xsd:choice>
        <xsd:attribute name="id" use="required" type="xsd:ID"/>
    </xsd:complexType>

    <xsd:element name="SoftwareRequirementsDocument" type="SoftwareRequirementsDocumentType"/>
    <xsd:complexType name="SoftwareRequirementsDocumentType">
        <xsd:sequence>
            <xsd:element ref="Section"/>

            <!-- Other global elements to be referenced here. -->
        </xsd:sequence>
        <xsd:attribute name="projectName" use="required" type="xsd:string"/>
        <!--<xsd:attribute name="id" use="required" type="xsd:ID"/>-->
    </xsd:complexType>

    <xsd:element name="Introduction" type="IntroductionType"/>
    <xsd:element name="Team" type="TeamType"/>
    <xsd:complexType name="TeamType">
        <xsd:sequence>
            <xsd:element name="TeamMember" type="TMType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="TMType">
        <xsd:choice minOccurs="0">
            <xsd:element name="Name" maxOccurs="1">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="isNewest" type="xsd:boolean" use="required"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="Role" minOccurs="1">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="isNewest" type="xsd:boolean" use="required"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
        </xsd:choice>

    </xsd:complexType>
    <xsd:complexType name="IntroductionType">
        <xsd:sequence>
            <xsd:element name="Team" type="TeamType"/>
            <xsd:element ref="Section" minOccurs="1" maxOccurs="unbounded"/>
            <!-- <xsd:element ref="Title"/>
            <xsd:element ref="Para" minOccurs="0" maxOccurs="unbounded"/>-->
        </xsd:sequence>
        <!--<xsd:attribute name="id" use="required" type="xsd:ID"/>-->
    </xsd:complexType>

    <xsd:element name="Title" type="xsd:string"/>



    <xsd:complexType name="TitleType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string"/>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:element name="Para" type="xsd:string"/>
    <xsd:simpleType name="ParaType">

        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>

    <xsd:element name="GeneralDescription" type="GeneralDescriptionType"/>
    <xsd:complexType name="GeneralDescriptionType">

        <!-- This is just an example. It may be more complex than this... -->
        <xsd:sequence>
            <xsd:element ref="Title" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element ref="Section" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" use="optional" type="xsd:ID"/>
    </xsd:complexType>

    <xsd:element name="SpecificRequirements" type="SpecificRequirementsType"/>
    <xsd:element name="Section" type="SectionType"/>
    <xsd:complexType name="SectionType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">

            <xsd:element ref="Title" minOccurs="0"/>
            <xsd:element ref="Para" minOccurs="0"/>
            <xsd:element ref="Requirement" minOccurs="0"/>
            <xsd:element ref="Image" minOccurs="0"/>
            <xsd:element ref="Section" minOccurs="0"/>
            <xsd:element name="TestResult" minOccurs="0" type="xsd:boolean"/>
            <xsd:element ref="ApprovedBy" minOccurs="0"/>
            <xsd:element name="Ref" minOccurs="0" type="xsd:IDREF"/>
            <xsd:element name="Comment" minOccurs="0" type="xsd:string"/>
        </xsd:choice>
        <xsd:attribute name="id" use="optional" type="xsd:ID"/>
        <xsd:attribute name="name" use="optional" type="xsd:string"/>
    </xsd:complexType>
    <xsd:element name="Image" type="ImageType"/>
    <xsd:complexType name="ImageType">
        <xsd:attribute name="id"/>
    </xsd:complexType>
    <xsd:complexType name="SpecificRequirementsType">
        <!-- This is just an example. It may be more complex than this... -->
        <xsd:sequence>
            <xsd:element name="Section" type="SectionType" minOccurs="1" maxOccurs="unbounded"/>

        </xsd:sequence>
        <xsd:attribute name="id" use="optional" type="xsd:ID"/>
    </xsd:complexType>

    <xsd:element name="ApprovedBy" type="ApprovedByType"/>
    <xsd:complexType name="ApprovedByType">
        <xsd:sequence>
            <xsd:element name="Name" type="xsd:string"/>
            <xsd:element ref="Para" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="Requirement" type="RequirementType"> </xsd:element>
    <xsd:complexType name="RequirementType">
        <!-- This is just an example. It may be more complex than this... -->
        <xsd:sequence>
            <xsd:element ref="Title" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element ref="Para" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element ref="Requirement" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" use="optional" type="xsd:ID"/>
        <!-- <xsd:attribute name="name" use="optional" type="xsd:string"/>-->
    </xsd:complexType>
    <xsd:element name="UseCaseDocument" type="UseCaseDocumentType"/>
    <xsd:complexType name="UseCaseDocumentType">

        <xsd:sequence>
            <xsd:element ref="Section" minOccurs="0" maxOccurs="unbounded"/>
            <!-- Other global elements to be referenced here. -->
        </xsd:sequence>

        <xsd:attribute name="id" use="optional" type="xsd:ID"/>
        <xsd:attribute name="projectName" use="required" type="xsd:string"/>
    </xsd:complexType>
    <xsd:element name="ActivityDiagram" type="ActivityDiagramType"/>
    <xsd:complexType name="ActivityDiagramType">
        <xsd:sequence>
            <xsd:element ref="Title" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element ref="Para" minOccurs="0" maxOccurs="unbounded"/>

        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:ID" use="required"/>
    </xsd:complexType>
    <xsd:element name="DesignDocument" type="DesignDocumentType"/>
    <xsd:complexType name="DesignDocumentType">
        <xsd:sequence>
            <xsd:element ref="Introduction"/>
            <!-- Other global elements to be referenced here. -->
        </xsd:sequence>
        <xsd:attribute name="id" use="required" type="xsd:ID"/>
    </xsd:complexType>

    <xsd:element name="TestCaseDocument" type="TestCaseDocumentType"/>
    <xsd:complexType name="TestCaseDocumentType">
        <xsd:sequence>
            <xsd:element ref="Section" minOccurs="1" maxOccurs="unbounded"/>
            <!-- Other global elements to be referenced here. -->
        </xsd:sequence>
        <!--<xsd:attribute name="id" use="required" type="xsd:ID"/>-->
        <xsd:attribute name="projectName" use="required" type="xsd:string"/>
    </xsd:complexType>
</xsd:schema>

=== UMDSeniorDesign/Lifecycledocs/XML XSD XSLT/NotionalTestCase.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="NotionalSRS12.xsl"?>
<ProjectLifecycleDocuments id="PL1.3" xmlns:xi="http://www.w3.org/2001/XInclude">
 
    <TestCaseDocument projectName="Lifecycle Documents with Requirements Tracking" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xi="http://www.w3.org/2001/XInclude" xsi:noNamespaceSchemaLocation="NotionalSchema2.xsd">
<Section id="TC1.0">
        <Title>Lifecycle Document Project Manager with Requirements Tracking</Title>
        <Para> The goal of this project is to create a protoype application capable of allowing a user to productively manage lifecycle documentation in XML without a previous XML experience. </Para>
        <Section id="TC1.1">
            <Title>Create Lifecycle Project</Title>
            <Section id="TC1.1.1">
                <Title>Form is displayed to user</Title>
                <Para>Form is displayed properly to user with appropriate textboxes and buttons.</Para>
                <TestResult>false</TestResult>
                <ApprovedBy>
                    <Name>Kevin</Name>
                    <Para>Comment</Para>
                </ApprovedBy>
                <Ref>RQ3.1.1</Ref>
                
               
            </Section>
            <Section id="TC1.1.2">
                <Title>Input project name</Title>
                <Para>Project name is an accepted string in textbox.  No special characters.</Para>
                <TestResult>false</TestResult>
                <ApprovedBy>
                    <Name>Pete</Name>
                </ApprovedBy>
                <Ref>RQ3.2.1</Ref>
                <Ref>RQ3.2.3</Ref>
            </Section>
            
            <Section id="TC1.1.3">
                <Title>Input template file location</Title>
                <Para>Template selected is a valid file type or is left blank.</Para>
                <TestResult>false</TestResult>
                <ApprovedBy>
                    <Name>Pete</Name>
                </ApprovedBy>
                <Ref>RQ3.1.4</Ref>
            </Section>
            
            <Section id="TC1.1.4">
                <Title>Template file is not of correct file type or does not exist</Title>
                <Para>Program prompts user with error message.</Para>
                <TestResult>false</TestResult>
                <ApprovedBy>
                    <Name>Jeremiah</Name>
                </ApprovedBy>
                <Ref>RQ3.2.1.2</Ref>
                <Ref>RQ3.2.1.5</Ref>
               
            </Section>
            
            <Section id="TC1.1.5">
                <Title>Select destination file location</Title>
                <Para>User is unable to input a destination and must use Browse button to select a folder to save the project in.</Para>
                <TestResult>false</TestResult>
                <ApprovedBy>
                    <Name>Ari</Name>
                </ApprovedBy>
                <Ref>RQ3.1.2</Ref>
                <Ref>RQ3.1.4</Ref>
                <Ref>RQ3.2.1.2</Ref>
                <Ref>RQ3.2.2.5</Ref>
                
            </Section>
            
            <Section id="TC1.1.6">
                <Title>Click cancel button or close window</Title>
                <Para> Create window is close and user is brought back to previous menu.</Para>
                <TestResult>false</TestResult>
                <ApprovedBy>
                    <Name>Ari</Name>
                </ApprovedBy>
                <Ref>RQ3.1.4</Ref>
            </Section>
            
            <Section id="TC1.1.7">
                <Title>Close Browse button</Title>
                <Para>user is prompted to select file destination and display destiniation in the textbox.</Para>
                <TestResult>false</TestResult>
                <ApprovedBy>
                    <Name>Kevin</Name>
                </ApprovedBy>
                <Ref>RQ3.1.1</Ref>
                <Ref>RQ3.1.4</Ref>
            </Section>
            
            <Section id="TC1.1.8">
                <Title>Click Create Button</Title>
                <Para>A blank document opens using Template selected.  The files saves in the destination selected with the name "Project Name"</Para>
                <TestResult>false</TestResult>
                <ApprovedBy>
                    <Name>Pete</Name>
                </ApprovedBy>
                <Ref>RQ3.1.1</Ref>
                <Ref>RQ3.1.4</Ref>
                <Ref>RQ3.2.1</Ref>
              
                
            </Section>
            
        </Section>
    </Section>
    
</TestCaseDocument>
</ProjectLifecycleDocuments>
