=== UMDSeniorDesign/Lifecycledocs/XML/NotionalSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xi="http://www.w3.org/2001/XInclude"
    elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="http://www.w3.org/2001/03/xml.xsd"/>
    <xsd:element name="ProjectLifecycleDocuments" type="ProjectLifecycleDocumentsType"/>
    <xsd:complexType name="ProjectLifecycleDocumentsType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="Team"/>
            <xsd:element name="file_location" maxOccurs="3"/>
            <xsd:element ref="SoftwareRequirementsDocument"/>
            <xsd:element ref="UseCaseDocument"/>
            <xsd:element ref="TestCaseDocument"/>
        </xsd:choice>
        <xsd:attribute name="projectName" use="required" type="xsd:string"/>
    </xsd:complexType>

    <xsd:element name="SoftwareRequirementsDocument" type="SoftwareRequirementsDocumentType"/>
    <xsd:complexType name="SoftwareRequirementsDocumentType">
        <xsd:sequence>
            <xsd:element name="StyleSheet" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <!--<xsd:attribute name="isNewest" type="xsd:boolean" use="required"/>
                                maybe incorporate isNewest here-->
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
            <xsd:element ref="Section" maxOccurs="unbounded"/>

            <!-- Other global elements to be referenced here. -->
        </xsd:sequence>
        <xsd:attribute name="projectName" use="required" type="xsd:string"/>
        <xsd:attribute ref="xml:base"/>
        <!--<xsd:attribute name="id" use="required" type="xsd:ID"/>-->
    </xsd:complexType>
    <xsd:element name="Team" type="TeamType"/>
    <xsd:complexType name="TeamType">
        <xsd:sequence>
            <xsd:element name="TeamMember" minOccurs="1" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:complexContent>
                        <xsd:extension base="TMType">
                            <xsd:attribute default="true" name="isNewest" type="xsd:boolean"/>
                        </xsd:extension>
                    </xsd:complexContent>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="TMType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="Name" maxOccurs="1">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="isNewest" type="xsd:boolean" use="required"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="Role" maxOccurs="1">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="isNewest" type="xsd:boolean" use="required"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="UIC" maxOccurs="1">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="isNewest" type="xsd:boolean" use="required"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
        </xsd:choice>

    </xsd:complexType>

    <xsd:element name="Title">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute name="isNewest" type="xsd:boolean"/>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="Para">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute name="isNewest" type="xsd:boolean"/>
                    <xsd:attribute name="index" type="xsd:string" use="optional"/>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="Section" type="SectionType"/>
    <xsd:complexType name="SectionType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">

            <xsd:element ref="Title" minOccurs="0"/>
            <xsd:element ref="Para" minOccurs="0"/>
            <xsd:element ref="Requirement" minOccurs="0"/>
            <xsd:element ref="Image" minOccurs="0"/>
            <xsd:element ref="Section" minOccurs="0"/>
            <xsd:element name="TestResult" minOccurs="0" type="xsd:boolean"/>
            <xsd:element ref="ApprovedBy" minOccurs="0"/>
            <xsd:element name="Ref" minOccurs="1" default="Ref">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="isNewest" type="xsd:boolean"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="Comment" minOccurs="0">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="isNewest" type="xsd:boolean"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
        </xsd:choice>
        <xsd:attribute name="id" use="optional" type="xsd:ID"/>
        <xsd:attribute name="name" use="optional" type="xsd:string"/>
        <xsd:attribute name="isNewest" type="xsd:boolean"/>
    </xsd:complexType>
    <xsd:element name="Image" type="ImageType"/>
    <xsd:complexType name="ImageType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="isNewest" type="xsd:boolean"/>
                <xsd:attribute name="id" type="xsd:ID"/>
            </xsd:extension>
        </xsd:simpleContent>
        
        
    </xsd:complexType>

    <xsd:element name="ApprovedBy" type="ApprovedByType"/>
    <xsd:complexType name="ApprovedByType">
        <xsd:sequence>
            <xsd:element name="Name" maxOccurs="1">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="isNewest" type="xsd:boolean" use="required"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="Date" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:dateTime">
                            <xsd:attribute name="isNewest" type="xsd:boolean" use="required"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
            <xsd:element ref="Para" minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute name="isNewest" type="xsd:boolean"/>
    </xsd:complexType>
    <xsd:element name="Requirement" type="RequirementType"> </xsd:element>
    <xsd:complexType name="RequirementType">
        <!-- This is just an example. It may be more complex than this... -->
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="Title" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element ref="Para" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element ref="Requirement" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="Ref" minOccurs="1" maxOccurs="unbounded" default="Ref">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="isNewest" type="xsd:boolean"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
        </xsd:choice>
        <xsd:attribute name="id" use="optional" type="xsd:ID"/>
        <!-- <xsd:attribute name="name" use="optional" type="xsd:string"/>-->
        <xsd:attribute name="isNewest" type="xsd:boolean"/>
    </xsd:complexType>
    <xsd:element name="UseCaseDocument" type="UseCaseDocumentType"/>
    <xsd:complexType name="UseCaseDocumentType">

        <xsd:sequence>
            <xsd:element name="StyleSheet" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <!--<xsd:attribute name="isNewest" type="xsd:boolean" use="required"/>
                                maybe incorporate isNewest here-->
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
            <xsd:element ref="Section" minOccurs="0" maxOccurs="unbounded"/>
            <!-- Other global elements to be referenced here. -->
        </xsd:sequence>
        <xsd:attribute ref="xml:base"/>
        <xsd:attribute name="projectName" use="required" type="xsd:string"/>
    </xsd:complexType>

    <xsd:element name="TestCaseDocument" type="TestCaseDocumentType"/>
    <xsd:complexType name="TestCaseDocumentType">
        <xsd:sequence>
            <xsd:element name="StyleSheet" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <!--<xsd:attribute name="isNewest" type="xsd:boolean" use="required"/>
                                maybe incorporate isNewest here-->
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
            <xsd:element ref="Section" minOccurs="1" maxOccurs="unbounded"/>
            <!-- Other global elements to be referenced here. -->
        </xsd:sequence>
        <!--<xsd:attribute name="id" use="required" type="xsd:ID"/>-->
        <xsd:attribute ref="xml:base"/>
        <xsd:attribute name="projectName" use="required" type="xsd:string"/>
    </xsd:complexType>
</xsd:schema>

=== UMDSeniorDesign/Lifecycledocs/documentXSL/NotionalTestCase.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="documentXSL.xsl"?>
 
<TestCaseDocument xml:base="ProjectLifecycleDocuments.xml" projectName="Lifecycle Documents with Requirements Tracking" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xi="http://www.w3.org/2001/XInclude" xsi:noNamespaceSchemaLocation="NotionalSchema.xsd" >
    
    <Section isNewest="true" id="TC1.0">
        <Title isNewest="true">Lifecycle Document Project Manager with Requirements Tracking</Title>
        <Para isNewest="true"> The goal of this project is to create a protoype application capable of allowing a user to productively manage lifecycle documentation in XML without a previous XML experience. </Para>
        <Section isNewest="true" id="TC1.1">
            <Title>Display splash screen.</Title>
            <Section isNewest="true" id="TC1.1.1">
                <Title>Buttons and textbox are displayed</Title>
                <Para>New Project, Open Project, and Browse buttons are displayed, as well as a textbox.</Para>
                <TestResult>false</TestResult>
                <ApprovedBy isNewest="true">
                    <Name isNewest="true">Pete</Name>
                    <Date isNewest="true">2004-04-12T13:20:15.5</Date>
                    <Para isNewest="true">This is getting the date element.</Para>
                </ApprovedBy>
                <Ref isNewest="true"></Ref>
                <Ref isNewest="true"></Ref>
            </Section>
            <Section isNewest="true" id="TC1.1.2">
                <Title>Title and sponsor image are displayed</Title>
                <Para>Title is displayed and sponsor image is clickable href.</Para>
                <TestResult>false</TestResult>
                <ApprovedBy isNewest="true">
                    <Name isNewest="true"></Name>
                    <Para isNewest="true"></Para>
                </ApprovedBy>
                <Ref isNewest="true"></Ref>
                <Ref isNewest="true"></Ref>
            </Section>
        </Section>
        
        <Section isNewest="true" id="TC1.2">
            <Title>Click browse button</Title>
            <Para>Browse button displays file directory for user to select projectXML.</Para>
            <TestResult>false</TestResult>
            <ApprovedBy isNewest="true">
                <Name isNewest="true"></Name>
                <Para isNewest="true"></Para>
            </ApprovedBy>
            <Ref isNewest="true"></Ref>
            <Ref isNewest="true"></Ref>
            <Section isNewest="true" id="TC1.2.1">
                <Title>User selects valid Project file</Title>
                <Para>Project is opened if correct file is chosen. If not, the user is prompted with an error.</Para>
                <TestResult>false</TestResult>
                <ApprovedBy>
                    <Name isNewest="false"></Name>
                </ApprovedBy>
                <Ref></Ref>
            </Section>
            
            <Section isNewest="true" id="TC1.2.2">
                <Title>Textbox contains file location</Title>
                <Para>Fills textbox with file location.</Para>
                <TestResult>false</TestResult>
                <ApprovedBy>
                    <Name isNewest="false"></Name>
                </ApprovedBy>
                <Ref></Ref>
            </Section>
            
            <Section isNewest="true" id="TC1.2.3">
                <Title>Team member information is displayed</Title>
                <Para>Properly display the XSL containing team member names, file count, and buttons to remove team members.</Para>
                <TestResult>false</TestResult>
                <ApprovedBy>
                    <Name isNewest="false"></Name>
                </ApprovedBy>
                <Ref></Ref>
            </Section>
            
            <Section isNewest="true" id="TC1.2.4">
                <Title>Open project is clicked</Title>
                <Para>If project file is valid, project is opened in new view.hta. If project file is not valid, user is prompted with error.</Para>
                <TestResult>false</TestResult>
                <ApprovedBy>
                    <Name isNewest="false"></Name>
                </ApprovedBy>
                <Ref></Ref>
            </Section>
            
        </Section>
        <Section isNewest="true" id="TC1.3">
            <Title>Open project is clicked with empty textbox</Title>
            <Para>User is prompted with error message: Please select a project to open!</Para>
            <TestResult>false</TestResult>
            <ApprovedBy>
                <Name isNewest="false"></Name>
            </ApprovedBy>
            <Ref></Ref>
        </Section>
        <Section isNewest="true" id="TC1.4">
            <Title>New Project is clicked</Title>
            <Para>User is prompted with textbox to enter project name.</Para>
            <TestResult>false</TestResult>
            <ApprovedBy>
                <Name isNewest="false"></Name>
            </ApprovedBy>
            <Ref></Ref>
            
            <Section isNewest="true" id="TC1.4.1">
                <Title>User clicks cancel</Title>
                <Para>Textbox is closed and user is brought back to splash screen.</Para>
                <TestResult>false</TestResult>
                <ApprovedBy>
                    <Name isNewest="false"></Name>
                </ApprovedBy>
                <Ref></Ref>
            </Section>
            
            <Section isNewest="true" id="TC1.4.2">
                <Title>User clicks OK</Title>
                <Para>If the project name is valid, user is directed to view.hta. Otherwise, user is asked to enter a valid project name.</Para>
                <TestResult>false</TestResult>
                <ApprovedBy>
                    <Name isNewest="false"></Name>
                </ApprovedBy>
                <Ref></Ref>
            </Section>
        </Section>
        
    </Section>
    
</TestCaseDocument>

=== UMDSeniorDesign/Lifecycledocs/Projects/ProjectLifecycleDocuments.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="ProjectXSL.xsl"?>
<!-- <root:ProjectLifeCycleDocuments -->
<ProjectLifecycleDocuments projectName="Interactive Lifecycle Document Development with Requirements Tracking" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xi="http://www.w3.org/2001/XInclude" xsi:noNamespaceSchemaLocation="NotionalSchema.xsd">
	<Team>
		<TeamMember isNewest="true">
			<Name isNewest="true">Jeremiah Butler</Name>
			<UIC isNewest="true">UMASSD-2</UIC>
			<Role isNewest="true">Team Lead</Role>
		</TeamMember>
		<TeamMember isNewest="true">
			<Name isNewest="true">Peter Magalhaes</Name>
			<UIC isNewest="true">UMASSD-9</UIC>
			<Role isNewest="true">Team Member</Role>
		</TeamMember>
		<TeamMember isNewest="true">
			<Name isNewest="true">Aria Ushani</Name>
			<Role isNewest="true">Team Member</Role>
		</TeamMember>
		<TeamMember isNewest="false">
			<Name isNewest="true">Palmer</Name>
			<Role isNewest="true">Team</Role>
		</TeamMember>
		<TeamMember isNewest="false">
			<Name isNewest="true">New</Name>
			<UIC isNewest="true"></UIC>
			<Role isNewest="true">New</Role>
		</TeamMember>
		<TeamMember isNewest="false">
			<Name isNewest="true">New </Name>
			<UIC isNewest="true"></UIC>
			<Role isNewest="true">Role</Role>
		</TeamMember>
		<TeamMember isNewest="false">
			<Name isNewest="true">new</Name>
			<UIC isNewest="true"></UIC>
			<Role isNewest="true">role</Role>
		</TeamMember>
		<TeamMember isNewest="false">
			<Name isNewest="true">person</Name>
			<UIC isNewest="true"></UIC>
			<Role isNewest="true">add</Role>
		</TeamMember>
		<TeamMember isNewest="false">
			<Name isNewest="true">r</Name>
			<UIC isNewest="true"></UIC>
			<Role isNewest="true">g</Role>
		</TeamMember>
		<TeamMember isNewest="false">
			<Name isNewest="true">j</Name>
			<UIC isNewest="true"></UIC>
			<Role isNewest="true">k</Role>
		</TeamMember>
	</Team>
	<file_location>
		<xi:include href="NotionalSRS.xml" parse="xml">
			<xi:fallback>
				<p>The included document was not found!</p>
			</xi:fallback>
		</xi:include>
	</file_location>
	<file_location>
		<xi:include href="NotionalTestCase.xml">
			<xi:fallback>
				<p>The included document was not found!</p>
			</xi:fallback>
		</xi:include>
	</file_location>
	<file_location>
		<xi:include href="NotionalUseCase.xml">
			<xi:fallback>
				<p>The included document was not found!</p>
			</xi:fallback>
		</xi:include>
	</file_location>
</ProjectLifecycleDocuments>

=== UMDSeniorDesign/Lifecycledocs/XML/UseCase.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="NotionalUseCaseXSL.xsl"?>
<UseCaseDocument xml:base="projectName.xml" projectName="Lifecycle Documents with Requirements Tracking" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NotionalSchema.xsd">
	<Section isNewest="true" name="Introduction" id="UC1.0">
		<Title isNewest="true">PROJECT TITLE</Title>
		<Para isNewest="true" index="0">INSERT PROJECT GOAL</Para>
	</Section>
	<Section isNewest="true" name="UseCase" id="UC1.1">
		<Title isNewest="true">USE CASES</Title>
		<Requirement isNewest="true" id="UC1.1.1">
			<Title isNewest="true">CREATE PROJECT</Title>
			<Requirement isNewest="true" id="UC1.1.1.1">
				<Title isNewest="true">INSERT DESCRIPTION</Title>
				<Para isNewest="true" index="0">INSERT PROJECT DESCRIPTION, PRE-POST CONDITIONS, ETC. </Para>
			</Requirement>
		</Requirement>
	</Section>
</UseCaseDocument>

=== UMDSeniorDesign/Lifecycledocs/RTM/updated docs wRTM/User Manual/XML/User Manual.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="documentXSL.xsl"?>

<UseCaseDocument xml:base="ProjectLifecycleDocuments.xml" projectName="User Manual for Lifecycle Documents with Requirements Tracking" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NotionalSchema.xsd">

    <Section isNewest="true" name="Introductions" id="UC1.0">
        <Title isNewest="true">Introduction</Title>
        <Para isNewest="true" index="0">Welcome to the User Manual for Lifecycle Documents with Requirements Tracking.</Para>
        <Para isNewest="true" index="1">This application is used to aid in requirements tracking throughout the development of these documents. It offers users a way to keep track of documents within projects, generate deliverables automatically, and preview documents.</Para> 
        <Para isNewest="true" index="2">This manual supplements the user with basic how-to instructions, to familiarize the user the the graphical user interface. Anything outside the scope of this document should seek technican assistance.</Para>
        <Section isNewest="true" id="UC1.1">
            <Title isNewest="true">Copyright</Title>
            <Para isNewest="true" index="0">This application was created at the expense of Naval Undersea Warfare Center Division Newport in combination with the University of Massachusetts, Department of Computer Science.</Para>
        </Section>
        <Section isNewest="true" id="UC1.2">
            <Title isNewest="true">Features</Title>
            <Para isNewest="true" index="0">Easy-to-Use interface that requires minimal training to operate, and accommodates for users who have no coding experience to create XML documentation.</Para>
            <Para isNewest="true" index="1">Document previews allow the user to get an alternate visual representation of the data entered into the system. This document preview displays the document in an easily readable format to help the user to track their progress through the document.</Para>
            <Para isNewest="true" index="2">Convert the project XML documents to HTML, with just a few clicks. You can select either a single XML document from the project, or convert the entire project into HTML.</Para>
            <Para isNewest="true" index="3">Auto-Generate deliverables instantly. The application will aid in tracking requirements through verious phases of development in each document. Requirements tracking information can be generated and converted to HTML quickly</Para>
            <Para isNewest="true" index="4">Standalone application for the Windows environment, allow multi-version capatibility. The application has been tested on Windows 7 and Windows 8 to ensure robustness for the future.</Para>
        </Section>
    </Section>
    <Section isNewest="true" id="UC2.0">
        <Title isNewest="true">Getting Started</Title>
        <Image>../Images/splash screen.jpg</Image>
        <Section isNewest="true" id="UC2.1">
            <Title isNewest="true">Requirements</Title>
            <Para isNewest="true" index="0">PC using Microsoft Windows operating system.</Para>
            <Para isNewest="true" index="1">User is capable of using Windows OS.</Para>
        </Section>
        <Section isNewest="true" id="UC2.2">
            <Title isNewest="true">Installation and Execution</Title>
            <Para isNewest="true" index="0">Installation is simple and straight forward, just decompress the project zip, and execute the index.hta that resides in the HTA folder of the directory structure.</Para>
            
        </Section>
    </Section>
    <Section isNewest="true" id="UC3.0">
        <Title isNewest="true">Projects</Title>
        <Section isNewest="true" id="UC3.1">
            <Title isNewest="true">Creating a project</Title>
            <Para isNewest="true" index="0">PC using Microsoft Windows operating system.</Para>
            <Para isNewest="true" index="1">User is capable of using Windows OS.</Para>
        </Section>
        <Section isNewest="true" id="UC3.2">
            <Title isNewest="true">Inon</Title>
            <Para isNewest="true" index="0">Inore.</Para>
        </Section>
    </Section>
</UseCaseDocument>

=== UMDSeniorDesign/Lifecycledocs/XML/projectSRS.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="NotionalSRSXSL.xsl"?>
<SoftwareRequirementsDocument xml:base="projectName.xml" projectName="Lifecycle Documents with Requirements Tracking" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xi="http://www.w3.org/2001/XInclude" xsi:noNamespaceSchemaLocation="NotionalSchema.xsd">
	<Section isNewest="true" id="RQ1.0">
		<Title isNewest="true">Introduction</Title>
		<Para isNewest="true" index="0">INSERT INTRODUCTION 
	  </Para>
		<Section isNewest="true" id="RQ1.1">
			<Title isNewest="true">Purpose</Title>
			<Para isNewest="true" index="0">INSERT PURPOSE
			</Para>
		</Section>
		<Section isNewest="true" id="RQ1.2">
			<Title isNewest="true">Scope</Title>
			<Para isNewest="true" index="0">INSERT SCOPE
		</Para>
		</Section>
		<Section isNewest="true" id="RQ1.3">
			<Title isNewest="true">Definitions </Title>
			<Para isNewest="true" index="0">INSERT DEFINITIONS</Para>
			<Para isNewest="true" index="1">EXAMPLE: </Para>
			<Para isNewest="true" index="2">HTML - HyperText Mark-up Language</Para>
			<Para isNewest="true" index="3">XML - Extensible Mark-up Language</Para>
		</Section>
		<Section isNewest="true" id="RQ1.4">
			<Title isNewest="true">Overview</Title>
			<Para isNewest="true" index="0">INSERT OVERVIEW 
		</Para>
		</Section>
	</Section>
	<!--SECTION 2-->
	<Section isNewest="true" id="RQ2.0">
		<Title isNewest="true">General Description</Title>
		<Para isNewest="true" index="0">INSERT GENERAL DESCRIPTION</Para>
		<Section isNewest="true" id="RQ2.1">
			<Title isNewest="true">Product Perspective </Title>
			<Para isNewest="true" index="0">INSERT PRODUCT PERSPECTIVE
  	</Para>
		</Section>
		<Section isNewest="true" id="RQ2.2">
			<Title isNewest="true">Product Functions </Title>
			<Para isNewest="true" index="0">INSERT PRODUCT FUNCTIONS 
  	</Para>
		</Section>
		<Section isNewest="true" id="RQ2.3">
			<Title isNewest="true">User Characteristics</Title>
			<Para isNewest="true" index="0">INSERT USER CHARACTERISTICS
      </Para>
		</Section>
		<Section isNewest="true" id="RQ2.4">
			<Title isNewest="true">General Constraints</Title>
			<Para isNewest="true" index="0">INSERT PRODUCT CONTRAINTS</Para>
		</Section>
		<Section isNewest="true" id="RQ2.5">
			<Title isNewest="true">Assumptions</Title>
			<Para isNewest="true" index="0">INSERT ASSUMPTIONS</Para>
		</Section>
	</Section>
	<!--END Section 2-->
	<!--SECTION 3-->
	<Section isNewest="true" id="RQ3.0">
		<Title isNewest="true">Specific Requirements</Title>
		<Para isNewest="true" index="0">INSERT SPECIFIC REQUIREMENTS</Para>
		<Section isNewest="true" id="RQ3.1">
			<Title isNewest="true">External Interface Requirements</Title>
			<Para isNewest="true" index="0">INSERT EXTERNAL INTERFACE REQUIREMENTS</Para>
			<Requirement isNewest="true" id="RQ3.1.1">
				<Title isNewest="true"> User Interfaces </Title>
				<Para isNewest="true" index="0">INSERT USER INTERFACE DESCRIPTION
		</Para>
			</Requirement>
			<Requirement isNewest="true" id="RQ3.1.2">
				<Title isNewest="true">HardwareInterfaces</Title>
				<Para isNewest="true" index="0">INSERT HARDWARE INTERFACE DESCRIPTION
  		</Para>
			</Requirement>
			<Requirement isNewest="true" id="RQ3.1.3">
				<Title isNewest="true">Software Interfaces</Title>
				<Para isNewest="true" index="0">INSERT SOFTWARE INTERFACE DESCRIPTION</Para>
			</Requirement>
			<Requirement isNewest="true" id="RQ3.1.4">
				<Title isNewest="true">Communication Interfaces</Title>
				<Para isNewest="true" index="0">INSERT COMMUNICATION INTERFACE DESCRIPTION </Para>
			</Requirement>
		</Section>
	</Section>
	<Section isNewest="true" id="RQ3.2">
		<Title isNewest="true">Functional Requirements</Title>
		<Para isNewest="true" index="0">INSERT FUNCTIONAL REQUIREMENTS</Para>
	</Section>
	<Section isNewest="true" id="RQ3.3">
		<Title isNewest="true">Use Case</Title>
		<Para isNewest="true" index="0">INSERT USE CASES</Para>
	</Section>
</SoftwareRequirementsDocument>
