=== UMDSeniorDesign/Lifecycledocs/XML/NotionalSRS13_no_errors_but_unfinished.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    attributeFormDefault="unqualified">

    <xsd:element name="ProjectLifecycleDocuments" type="ProjectLifecycleDocumentsType"/>
    <xsd:complexType name="ProjectLifecycleDocumentsType">
        <xsd:sequence>
            <xsd:element ref="SoftwareRequirementsDocument"/>
            <xsd:element ref="UseCaseDocument"/>
            <xsd:element ref="TestCaseDocument"/>
        </xsd:sequence>
        <xsd:attribute name="id" use="required" type="xsd:ID"/>
    </xsd:complexType>

    <xsd:element name="SoftwareRequirementsDocument" type="SoftwareRequirementsDocumentType"/>
    <xsd:complexType name="SoftwareRequirementsDocumentType">
        <xsd:sequence>
            <xsd:element ref="Introduction"/>
            <xsd:element ref="GeneralDescription"/>
            <xsd:element ref="SpecificRequirements"/>

            <!-- Other global elements to be referenced here. -->
        </xsd:sequence>
        <xsd:attribute name="projectName" use="required" type="xsd:string"/>
        <!--<xsd:attribute name="id" use="required" type="xsd:ID"/>-->
    </xsd:complexType>

    <xsd:element name="Introduction" type="IntroductionType"/>
    <xsd:element name="Team" type="TeamType"/>
    <xsd:complexType name="TeamType">
        <xsd:sequence>
            <xsd:element name="TeamMember" type="TMType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="TMType">
        <xsd:sequence>
            <xsd:element name="Name" maxOccurs="1" type="xsd:string"/>
            <xsd:element name="Role" maxOccurs="1" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="IntroductionType">
        <xsd:sequence>
            <xsd:element name="Team" type="TeamType"/>
            <xsd:element ref="Section" minOccurs="1" maxOccurs="unbounded"/>
            <!-- <xsd:element ref="Title"/>
            <xsd:element ref="Para" minOccurs="0" maxOccurs="unbounded"/>-->
        </xsd:sequence>
        <!--<xsd:attribute name="id" use="required" type="xsd:ID"/>-->
    </xsd:complexType>

    <xsd:element name="Title" type="xsd:string"/>



    <xsd:complexType name="TitleType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string"/>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:element name="Para" type="xsd:string"/>
    <xsd:simpleType name="ParaType">
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>

    <xsd:element name="GeneralDescription" type="GeneralDescriptionType"/>
    <xsd:complexType name="GeneralDescriptionType">

        <!-- This is just an example. It may be more complex than this... -->
        <xsd:sequence>
            <xsd:element ref="Title" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element ref="Section" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" use="optional" type="xsd:ID"/>
    </xsd:complexType>

    <xsd:element name="SpecificRequirements" type="SpecificRequirementsType"/>
    <xsd:element name="Section" type="SectionType"/>
    <xsd:complexType name="SectionType">
        <xsd:sequence>

            <xsd:element ref="Title" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element ref="Para" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element ref="Requirement" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element ref="Image" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" use="optional" type="xsd:ID"/>
        <xsd:attribute name="name" use="optional" type="xsd:string"/>
    </xsd:complexType>
    <xsd:element name="Image" type="ImageType"/>
    <xsd:complexType name="ImageType">
        <xsd:sequence>
            <!--Learn how to deal with images--> </xsd:sequence>

    </xsd:complexType>
    <xsd:complexType name="SpecificRequirementsType">
        <!-- This is just an example. It may be more complex than this... -->
        <xsd:sequence>
            <xsd:element name="Section" type="SectionType" minOccurs="1" maxOccurs="unbounded"/>

        </xsd:sequence>
        <xsd:attribute name="id" use="optional" type="xsd:ID"/>
    </xsd:complexType>

    <xsd:element name="Requirement" type="RequirementType"> </xsd:element>

    <xsd:complexType name="RequirementType">
        <!-- This is just an example. It may be more complex than this... -->
        <xsd:sequence>
            <xsd:element ref="Title" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element ref="Para" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element ref="subReq" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" use="optional" type="xsd:ID"/>
        <!-- <xsd:attribute name="name" use="optional" type="xsd:string"/>-->
    </xsd:complexType>

    <xsd:element name="subReq" type="subReqType"/>
    <xsd:element name="subTitle" type="xsd:string"/>

    <xsd:complexType name="subTitleType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string"> </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="subReqType">
        <xsd:sequence>
            <xsd:element ref="subTitle" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element ref="Para" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:ID"/>
    </xsd:complexType>


    <xsd:complexType name="AnalysisModelType"/>
    <xsd:element name="UseCaseDocument" type="UseCaseDocumentType"/>
    <xsd:complexType name="UseCaseDocumentType">
        <xsd:sequence>
            <xsd:element ref="Introduction"/>
            <xsd:element ref="Section"/>
            <!-- Other global elements to be referenced here. -->
        </xsd:sequence>
        <xsd:attribute name="id" use="optional" type="xsd:ID"/>
        <xsd:attribute name="projectName" use="required" type="xsd:string"/>
    </xsd:complexType>
    <xsd:element name="ActivityDiagram" type="ActivityDiagramType"/>
    <xsd:complexType name="ActivityDiagramType">
        <xsd:sequence>
            <xsd:element ref="Title" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element ref="Para" minOccurs="0" maxOccurs="unbounded"/>

        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:ID" use="required"/>
    </xsd:complexType>
    <xsd:element name="DesignDocument" type="DesignDocumentType"/>
    <xsd:complexType name="DesignDocumentType">
        <xsd:sequence>
            <xsd:element ref="Introduction"/>
            <!-- Other global elements to be referenced here. -->
        </xsd:sequence>
        <xsd:attribute name="id" use="required" type="xsd:ID"/>
    </xsd:complexType>

    <xsd:element name="TestCaseDocument" type="TestCaseDocumentType"/>
    <xsd:complexType name="TestCaseDocumentType">
        <xsd:sequence>
            <xsd:element ref="Introduction"/>
            <!-- Other global elements to be referenced here. -->
        </xsd:sequence>
        <xsd:attribute name="id" use="required" type="xsd:ID"/>
    </xsd:complexType>
</xsd:schema>

=== UMDSeniorDesign/Lifecycledocs/XML/NotionalTestCase.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="NotionalSRS12.xsl"?>

<TestCaseDocument projectName="Lifecycle Documents with Requirements Tracking" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NotionalSRS13_no_errors_but_unfinished.xsd">
    
    <Section id="TC1.0">
        <Title>Lifecycle Document Project Manager with Requirements Tracking</Title>
        <Para> The goal of this project is to create a protoype application capable of allowing a user to productively manage lifecycle documentation in XML without a previous XML experience. </Para>
    </Section>
    <Section id="TC1.1">
        <Title>Create Lifecycle Project</Title>
        <Requirement id="TC1.1.1">
            <Title>Input Project Name</Title>
            <Para>Expected Output: </Para>
        </Requirement>
    </Section>
    
</TestCaseDocument>
