=== UMDSeniorDesign/Lifecycledocs/XML/NotionalSchema2.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xi="http://www.w3.org/2001/XInclude"
    elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xsd:element name="ProjectLifecycleDocuments" type="ProjectLifecycleDocumentsType"/>
    <xsd:complexType name="ProjectLifecycleDocumentsType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="Team"/>
            <xsd:element ref="SoftwareRequirementsDocument"/>
            <xsd:element ref="UseCaseDocument"/>
            <xsd:element ref="TestCaseDocument"/>
        </xsd:choice>
        <xsd:attribute name="projectName" use="required" type="xsd:string"/>
    </xsd:complexType>

    <xsd:element name="SoftwareRequirementsDocument" type="SoftwareRequirementsDocumentType"/>
    <xsd:complexType name="SoftwareRequirementsDocumentType">
        <xsd:sequence>
            <xsd:element ref="Section" maxOccurs="unbounded"/>

            <!-- Other global elements to be referenced here. -->
        </xsd:sequence>
        <xsd:attribute name="projectName" use="required" type="xsd:string"/>
        <!--<xsd:attribute name="id" use="required" type="xsd:ID"/>-->
    </xsd:complexType>

    <xsd:element name="Introduction" type="IntroductionType"/>
    <xsd:element name="Team" type="TeamType"/>
    <xsd:complexType name="TeamType">
        <xsd:sequence>
            <xsd:element name="TeamMember" type="TMType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="TMType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="Name" maxOccurs="1">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="isNewest" type="xsd:boolean" use="required"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="Role" maxOccurs="1">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="isNewest" type="xsd:boolean" use="required"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
        </xsd:choice>

    </xsd:complexType>
    <xsd:complexType name="IntroductionType">
        <xsd:sequence>
            <xsd:element name="Team" type="TeamType"/>
            <xsd:element ref="Section" minOccurs="1" maxOccurs="unbounded"/>
            <!-- <xsd:element ref="Title"/>
            <xsd:element ref="Para" minOccurs="0" maxOccurs="unbounded"/>-->
        </xsd:sequence>
        <!--<xsd:attribute name="id" use="required" type="xsd:ID"/>-->
    </xsd:complexType>

    <xsd:element name="Title">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute name="isNewest" type="xsd:boolean"/>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="Para">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute name="isNewest" type="xsd:boolean"/>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="Section" type="SectionType"/>
    <xsd:complexType name="SectionType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">

            <xsd:element ref="Title" minOccurs="0"/>
            <xsd:element ref="Para" minOccurs="0"/>
            <xsd:element ref="Requirement" minOccurs="0"/>
            <xsd:element ref="Image" minOccurs="0"/>
            <xsd:element ref="Section" minOccurs="0"/>
            <xsd:element name="TestResult" minOccurs="0" type="xsd:boolean"/>
            <xsd:element ref="ApprovedBy" minOccurs="0"/>
            <xsd:element name="Ref" minOccurs="0">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="isNewest" type="xsd:boolean"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="Comment" minOccurs="0">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="isNewest" type="xsd:boolean"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
        </xsd:choice>
        <xsd:attribute name="id" use="optional" type="xsd:ID"/>
        <xsd:attribute name="name" use="optional" type="xsd:string"/>
        <xsd:attribute name="isNewest" type="xsd:boolean"/>
    </xsd:complexType>
    <xsd:element name="Image" type="ImageType"/>
    <xsd:complexType name="ImageType">
        <xsd:attribute name="id" type="xsd:ID"/>
        <xsd:attribute name="isNewest" type="xsd:boolean"/>
    </xsd:complexType>

    <xsd:element name="ApprovedBy" type="ApprovedByType"/>
    <xsd:complexType name="ApprovedByType">
        <xsd:sequence>
            <xsd:element name="Name" type="xsd:string"/>
            <xsd:element ref="Para" minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute name="isNewest" type="xsd:boolean"/>
    </xsd:complexType>
    <xsd:element name="Requirement" type="RequirementType"> </xsd:element>
    <xsd:complexType name="RequirementType">
        <!-- This is just an example. It may be more complex than this... -->
        <xsd:sequence>
            <xsd:element ref="Title" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element ref="Para" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element ref="Requirement" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" use="optional" type="xsd:ID"/>
        <!-- <xsd:attribute name="name" use="optional" type="xsd:string"/>-->
        <xsd:attribute name="isNewest" type="xsd:boolean"/>
    </xsd:complexType>
    <xsd:element name="UseCaseDocument" type="UseCaseDocumentType"/>
    <xsd:complexType name="UseCaseDocumentType">

        <xsd:sequence>
            <xsd:element ref="Section" minOccurs="0" maxOccurs="unbounded"/>
            <!-- Other global elements to be referenced here. -->
        </xsd:sequence>

        <xsd:attribute name="id" use="optional" type="xsd:ID"/>
        <xsd:attribute name="projectName" use="required" type="xsd:string"/>
    </xsd:complexType>

    <xsd:element name="TestCaseDocument" type="TestCaseDocumentType"/>
    <xsd:complexType name="TestCaseDocumentType">
        <xsd:sequence>
            <xsd:element ref="Section" minOccurs="1" maxOccurs="unbounded"/>
            <!-- Other global elements to be referenced here. -->
        </xsd:sequence>
        <!--<xsd:attribute name="id" use="required" type="xsd:ID"/>-->
        <xsd:attribute name="projectName" use="required" type="xsd:string"/>
    </xsd:complexType>
</xsd:schema>

=== UMDSeniorDesign/Lifecycledocs/XML/NotionalSRS2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="NotionalXSL.xsl"?>


<SoftwareRequirementsDocument xml:base='ProjectLifecycleDocuments.xml' projectName="Lifecycle Documents with Requirements Tracking"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NotionalSchema2.xsd">

		
		<Section isNewest="true" id="RQ1.0">
			
		<Title isNewest="true">Introduction</Title>
			<Para isNewest="true">The Software Requirements Specification details the extent of NUWC’s Lifecycle Project Manager. The product’s main feature is it’s ability to create and manage lifecycle documents using a graphical user interface. The lifecycle documents will be organized and exported using an XML Schema. This can be accomplished by a user who has no knowledge of the XML language. This document will review all the basic functionality required for a user to edit, create, and manage lifecycle projects.
	  </Para>    
		</Section>
		
	<Section isNewest="true" id="RQ1.1">
		<Title isNewest="true">Purpose</Title>
		<Para isNewest="true"> To provide a detailed description of how the product will produce it’s lifecycle documents as well as edit and export them. It also overviews the basic functional requirements requested by the customer.
			</Para>
		</Section>
		
		<Section isNewest="true" id="RQ1.2">
			
		<Title isNewest="true">Scope</Title>
		<Para isNewest="true">The Lifecycle Project Manager will create and edit projects and lifecycle documents. It will serve as a cheap but easy to use software that allows users to input their own data and organize based on an XML schema. The product will export the lifecycle documents as PDF and HTML, as well as print out a requirements traceability matrix.
		</Para>
		</Section>
		<Section isNewest="true" id="RQ1.3">
		<Title isNewest="true">Definitions </Title>
		<Para isNewest="true">API - Application Programming Interface</Para>
		<Para isNewest="true">CSS - Cascading Style Sheet</Para>
		<Para isNewest="true">CSV - Comma Separated Value</Para>
		<Para isNewest="true">GUI - Graphical User Interface</Para>
		<Para isNewest="true">HTML - HyperText Markup Language</Para>
		<Para isNewest="true">JS - Javascript</Para>
		<Para isNewest="true">LC - Lifecycle</Para>
		<Para isNewest="true">NUWC - Naval Undersea Warfare Center Division Newport</Para>
		<Para isNewest="true">PDF - Portable Document Format</Para>
		<Para isNewest="true">RTM - Requirements Traceability Matrix</Para>
		<Para isNewest="true">UMASSD - University of Massachusetts: Dartmouth</Para>
		<Para isNewest="true">XML - Extensible Markup Language</Para>
		</Section>
		
		<Section isNewest="true" id="RQ1.4">
			
		<Title isNewest="true">Overview</Title>
		<Para isNewest="true">The SRS contains explicit details describing how the product is designed and implemented. It is organized in a top-down layered approach. The goal of this project is to create a protoype application capable of allowing a user to productively manage lifecycle documentation in XML without an previous XML experience. 
		</Para>
		</Section>
	
   
 <!--SECTION 2-->
 
  <Section isNewest="true" id="RQ2.0">
  	
  	<Title isNewest="true">General Description</Title>
  	<Section isNewest="true" id="RQ2.1">
	<Title isNewest="true">Product Perspective </Title>
  	<Para isNewest="true">Our project team design goal is to develop a software solution to the proposal offered by NUWC. The design will accommodate for previous user complaints and shortcoming. It will also replace manual spreadsheet entries into a database. The software will also automate the process of generating a RTM. It will be a new, self-contained, web-based solution that requires minimal constraints. The design goal is to provide a tabular method of viewing multiple documents simultaneously to promote user productivity.
  	</Para>
  		
  	</Section>
  	<Section isNewest="true" id="RQ2.2">
  		
  	<Title isNewest="true">Product Functions </Title>
  	<Para isNewest="true">The software will prompt the user to open a new project or create a new one. When the user selects new project it presents the user with a set default templates which have been checked against a defined XML schema. These templates will be saved with the filename specified by the user. The user can then edit these templates with their information. The user can define requirements which will be traced throughout other documents in the project. After the documents have been saved, the user can select to create a RTM (Requirement Traceability Matrix) from the XML templates which the user has created and modified. 
  	</Para>
  	</Section>
  	<Section isNewest="true" id="RQ2.3">
  	<Title isNewest="true">User Characteristics</Title>
      <Para isNewest="true">This product is intended to be used by a non-technical user who may have no knowledge of the XML language. There will be no user groups, or administrator authentications. The user will be assumed to have access once the user is able to log into the computer where the software is stored.
      </Para>
  	</Section>
  	<Section isNewest="true" id="RQ2.4">
  	<Title isNewest="true">General Constraints</Title>
     
      <Para isNewest="true">The software will run on a Microsoft Windows 7 platform within Microsoft Internet Explorer browser. </Para>
	  
      <Para isNewest="true">The use of a database is prohibited and there is also no Internet connection available.</Para>
	  
	  <Para isNewest="true">The software must implement an XML schema developed by the team. The schema helps keep the document structured and search-able. </Para>
	  
	  <Para isNewest="true">By using an XML schema and an XLST processor, the user will have the ability to export documents as either an HTML or PDF.</Para>  
  	</Section>
  	<Section isNewest="true" id="RQ2.5">
  	<Title isNewest="true">Assumptions</Title>
      <Para isNewest="true">One dependency would be the available browser. If this were to change our application may break or provide an unintended appearance or functionality to the user.</Para>
	  
      <Para isNewest="true"> product will create a directory for all of the created/edited LC documents, and the user will have permission on the local machine for the software to function as intended.</Para>
	  
	  <Para isNewest="true">The team must also assume the user is capable of creating and editing technical documentation. </Para>
	  
	  <Para isNewest="true">Lastly, one major assumption is user has no knowledge of XML and the user should have not have to see what is happening behind the scenes while creating the project and exporting the documents.
	  </Para>
  	</Section>
  </Section>
<!--END Section 2-->
  
<!--SECTION 3-->  
	
  <Section isNewest="true" id="RQ3.0">
  	<Title isNewest="true">Specific Requirements</Title>
  	<Section isNewest="true" id="RQ3.1">
  		<Title isNewest="true">External Interface Requirements</Title>
  	<Requirement isNewest="true" id="RQ3.1.1"> 
  		<Title isNewest="true"> User Interfaces </Title>
		<Para isNewest="true">The user interface should be easy to use and have simple text boxes and an active table of contents menu, and a preview of the document selected in a preview pane. Since the user is unaware of the XML back end implementation, a GUI must be driven from XML to allow for easy adaptation.
		</Para>
		<Requirement isNewest="true" id="RQ3.1.1.1">
			<Para isNewest="true">User is unaware of XML back end implementation.</Para>
		</Requirement>
		<Requirement isNewest="true" id="RQ3.1.1.2">
			<Para isNewest="true">System shall present a GUI to users that allow them to develop and edit lifecycle documents (i.e Requirements, Design, and Test)</Para>
		</Requirement>
		<Requirement isNewest="true" id="RQ3.1.1.3">
			<Para isNewest="true">Ability to view existing requirements, design elements and test cases shall be available at all times. </Para>
		</Requirement>
  	</Requirement>
  		
  		
  		<Requirement isNewest="true" id="RQ3.1.2">
  		<Title isNewest="true">HardwareInterfaces</Title>
  		<Para isNewest="true"> The application will be able to operate on a modern Microsoft Windows operating computer, that has an active installation of Microsoft Internet Explorer. Since there will be no network connection available, there is no requirement to interface to a network, however, the software solution will be web-based and address some scalability issues. All other hardware interfacing will be handled by the operating system, or the browser. 
  		</Para>
		<Requirement isNewest="true" id="RQ3.1.2.1"> 
			<Para isNewest="true"> All hardware interfacing is handled by the browser.</Para>
		</Requirement>
  		</Requirement>
		
		<Requirement isNewest="true" id="RQ3.1.3">
  		<Title isNewest="true">Software Interfaces</Title>
			<Para isNewest="true">The XML Schema will be developed by the team, and the RTM will be auto-generated upon request. The XSLT processor will be used to convert the XML lifecycle documentation into HTML or PDF documents. The software will also use Internet Explorer as the main software interface.</Para>
			<Requirement isNewest="true" id="RQ3.1.3.1">
				<Para isNewest="true">Must work with Internet Explorer 10.</Para>
			</Requirement>
			<Requirement isNewest="true" id="RQ3.1.3.2">
				<Para isNewest="true">Program should be capable of running XSLT processing for HTML and PDF output. An XML instance shall be transformed, via XSLT designed and developed by the team into an HTML-based interactive document.</Para>
			</Requirement>
			<Requirement isNewest="true" id="RQ3.1.3.3">
				<Para isNewest="true">System shall provide a mechanism to associate related parts of each document. (e.g. Requirement x is associated with design element y and test case z).</Para>
			</Requirement>
			<Requirement isNewest="true" id="RQ3.1.3.4">
				<Para isNewest="true">System shall produce XML instances conformant with an XML schema designed and developed by the team.</Para>
			</Requirement>
